version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - submodule
