# CMake generated Testfile for 
# Source directory: D:/emhash/tests
# Build directory: D:/emhash/tests/build_attack
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(reproduce_emhash8_bug "D:/emhash/tests/build_attack/reproduce_emhash8_bug.exe")
set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;137;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_verify "D:/emhash/tests/build_attack/test_verify.exe")
set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;140;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(quick_test8 "D:/emhash/tests/build_attack/quick_test8.exe")
set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;141;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash58 "D:/emhash/tests/build_attack/test_emhash58.exe")
set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;142;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_hidden_bugs8 "D:/emhash/tests/build_attack/test_hidden_bugs8.exe")
set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;143;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_extreme "D:/emhash/tests/build_attack/test_extreme.exe")
set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;144;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_interface_combo "D:/emhash/tests/build_attack/test_interface_combo.exe")
set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;145;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_verify "D:/emhash/tests/build_attack/test_emhash5_verify.exe")
set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;146;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash_allocator "D:/emhash/tests/build_attack/test_emhash_allocator.exe")
set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;147;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_functional_edge "D:/emhash/tests/build_attack/test_functional_edge.exe")
set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;148;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashset_allocator "D:/emhash/tests/build_attack/test_hashset_allocator.exe")
set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;149;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emilib_comprehensive "D:/emhash/tests/build_attack/test_emilib_comprehensive.exe")
set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;150;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_size_sweep "D:/emhash/tests/build_attack/test_size_sweep.exe")
set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;151;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashmap_full_api "D:/emhash/tests/build_attack/test_hashmap_full_api.exe")
set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;152;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashset_full_api "D:/emhash/tests/build_attack/test_hashset_full_api.exe")
set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;153;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_special_key_types "D:/emhash/tests/build_attack/test_special_key_types.exe")
set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;154;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_merge_correctness "D:/emhash/tests/build_attack/test_merge_correctness.exe")
set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;155;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(edge_test "D:/emhash/tests/build_attack/edge_test.exe")
set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;156;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_find_slot_bucket "D:/emhash/tests/build_attack/test_find_slot_bucket.exe")
set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;157;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_string_key_leak "D:/emhash/tests/build_attack/test_string_key_leak.exe")
set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;158;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_stress "D:/emhash/tests/build_attack/test_stress.exe")
set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;161;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_bad_hash_stress "D:/emhash/tests/build_attack/test_bad_hash_stress.exe")
set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;162;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(stress_fix "D:/emhash/tests/build_attack/stress_fix.exe")
set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;163;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(highload_test "D:/emhash/tests/build_attack/highload_test.exe")
set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;164;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_stress "D:/emhash/tests/build_attack/test_emhash5_stress.exe")
set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;165;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_hifi "D:/emhash/tests/build_attack/test_emhash5_hifi.exe")
set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;166;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_attack "D:/emhash/tests/build_attack/test_attack.exe")
set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;169;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(hash_attack5 "D:/emhash/tests/build_attack/hash_attack5.exe")
set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;170;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(hash_attack7 "D:/emhash/tests/build_attack/hash_attack7.exe")
set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;171;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
add_test(test_debug "D:/emhash/tests/build_attack/test_debug.exe")
set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;133;add_test;D:/emhash/tests/CMakeLists.txt;174;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
