# CMake generated Testfile for 
# Source directory: D:/emhash/tests
# Build directory: D:/emhash/build_asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(reproduce_emhash8_bug "D:/emhash/build_asan/Debug/reproduce_emhash8_bug.exe")
  set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;156;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(reproduce_emhash8_bug "D:/emhash/build_asan/Release/reproduce_emhash8_bug.exe")
  set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;156;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(reproduce_emhash8_bug "D:/emhash/build_asan/MinSizeRel/reproduce_emhash8_bug.exe")
  set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;156;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(reproduce_emhash8_bug "D:/emhash/build_asan/RelWithDebInfo/reproduce_emhash8_bug.exe")
  set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;156;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(reproduce_emhash8_bug NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_verify "D:/emhash/build_asan/Debug/test_verify.exe")
  set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;159;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_verify "D:/emhash/build_asan/Release/test_verify.exe")
  set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;159;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_verify "D:/emhash/build_asan/MinSizeRel/test_verify.exe")
  set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;159;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_verify "D:/emhash/build_asan/RelWithDebInfo/test_verify.exe")
  set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;159;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_verify NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(quick_test8 "D:/emhash/build_asan/Debug/quick_test8.exe")
  set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;160;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(quick_test8 "D:/emhash/build_asan/Release/quick_test8.exe")
  set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;160;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(quick_test8 "D:/emhash/build_asan/MinSizeRel/quick_test8.exe")
  set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;160;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(quick_test8 "D:/emhash/build_asan/RelWithDebInfo/quick_test8.exe")
  set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;160;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(quick_test8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emhash58 "D:/emhash/build_asan/Debug/test_emhash58.exe")
  set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;161;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emhash58 "D:/emhash/build_asan/Release/test_emhash58.exe")
  set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;161;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emhash58 "D:/emhash/build_asan/MinSizeRel/test_emhash58.exe")
  set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;161;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emhash58 "D:/emhash/build_asan/RelWithDebInfo/test_emhash58.exe")
  set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;161;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emhash58 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hidden_bugs8 "D:/emhash/build_asan/Debug/test_hidden_bugs8.exe")
  set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;162;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hidden_bugs8 "D:/emhash/build_asan/Release/test_hidden_bugs8.exe")
  set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;162;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hidden_bugs8 "D:/emhash/build_asan/MinSizeRel/test_hidden_bugs8.exe")
  set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;162;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hidden_bugs8 "D:/emhash/build_asan/RelWithDebInfo/test_hidden_bugs8.exe")
  set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;162;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_hidden_bugs8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_extreme "D:/emhash/build_asan/Debug/test_extreme.exe")
  set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;163;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_extreme "D:/emhash/build_asan/Release/test_extreme.exe")
  set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;163;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_extreme "D:/emhash/build_asan/MinSizeRel/test_extreme.exe")
  set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;163;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_extreme "D:/emhash/build_asan/RelWithDebInfo/test_extreme.exe")
  set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;163;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_extreme NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_interface_combo "D:/emhash/build_asan/Debug/test_interface_combo.exe")
  set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;164;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_interface_combo "D:/emhash/build_asan/Release/test_interface_combo.exe")
  set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;164;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_interface_combo "D:/emhash/build_asan/MinSizeRel/test_interface_combo.exe")
  set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;164;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_interface_combo "D:/emhash/build_asan/RelWithDebInfo/test_interface_combo.exe")
  set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;164;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_interface_combo NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emhash5_verify "D:/emhash/build_asan/Debug/test_emhash5_verify.exe")
  set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;165;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emhash5_verify "D:/emhash/build_asan/Release/test_emhash5_verify.exe")
  set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;165;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emhash5_verify "D:/emhash/build_asan/MinSizeRel/test_emhash5_verify.exe")
  set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;165;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emhash5_verify "D:/emhash/build_asan/RelWithDebInfo/test_emhash5_verify.exe")
  set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;165;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emhash5_verify NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emhash_allocator "D:/emhash/build_asan/Debug/test_emhash_allocator.exe")
  set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;166;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emhash_allocator "D:/emhash/build_asan/Release/test_emhash_allocator.exe")
  set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;166;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emhash_allocator "D:/emhash/build_asan/MinSizeRel/test_emhash_allocator.exe")
  set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;166;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emhash_allocator "D:/emhash/build_asan/RelWithDebInfo/test_emhash_allocator.exe")
  set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;166;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emhash_allocator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_functional_edge "D:/emhash/build_asan/Debug/test_functional_edge.exe")
  set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;167;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_functional_edge "D:/emhash/build_asan/Release/test_functional_edge.exe")
  set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;167;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_functional_edge "D:/emhash/build_asan/MinSizeRel/test_functional_edge.exe")
  set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;167;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_functional_edge "D:/emhash/build_asan/RelWithDebInfo/test_functional_edge.exe")
  set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;167;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_functional_edge NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hashset_allocator "D:/emhash/build_asan/Debug/test_hashset_allocator.exe")
  set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;168;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hashset_allocator "D:/emhash/build_asan/Release/test_hashset_allocator.exe")
  set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;168;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hashset_allocator "D:/emhash/build_asan/MinSizeRel/test_hashset_allocator.exe")
  set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;168;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hashset_allocator "D:/emhash/build_asan/RelWithDebInfo/test_hashset_allocator.exe")
  set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;168;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_hashset_allocator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emilib_comprehensive "D:/emhash/build_asan/Debug/test_emilib_comprehensive.exe")
  set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;169;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emilib_comprehensive "D:/emhash/build_asan/Release/test_emilib_comprehensive.exe")
  set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;169;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emilib_comprehensive "D:/emhash/build_asan/MinSizeRel/test_emilib_comprehensive.exe")
  set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;169;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emilib_comprehensive "D:/emhash/build_asan/RelWithDebInfo/test_emilib_comprehensive.exe")
  set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;169;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emilib_comprehensive NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_size_sweep "D:/emhash/build_asan/Debug/test_size_sweep.exe")
  set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;170;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_size_sweep "D:/emhash/build_asan/Release/test_size_sweep.exe")
  set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;170;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_size_sweep "D:/emhash/build_asan/MinSizeRel/test_size_sweep.exe")
  set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;170;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_size_sweep "D:/emhash/build_asan/RelWithDebInfo/test_size_sweep.exe")
  set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;170;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_size_sweep NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hashmap_full_api "D:/emhash/build_asan/Debug/test_hashmap_full_api.exe")
  set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;171;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hashmap_full_api "D:/emhash/build_asan/Release/test_hashmap_full_api.exe")
  set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;171;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hashmap_full_api "D:/emhash/build_asan/MinSizeRel/test_hashmap_full_api.exe")
  set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;171;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hashmap_full_api "D:/emhash/build_asan/RelWithDebInfo/test_hashmap_full_api.exe")
  set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;171;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_hashmap_full_api NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hashset_full_api "D:/emhash/build_asan/Debug/test_hashset_full_api.exe")
  set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;172;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hashset_full_api "D:/emhash/build_asan/Release/test_hashset_full_api.exe")
  set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;172;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hashset_full_api "D:/emhash/build_asan/MinSizeRel/test_hashset_full_api.exe")
  set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;172;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hashset_full_api "D:/emhash/build_asan/RelWithDebInfo/test_hashset_full_api.exe")
  set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;172;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_hashset_full_api NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_special_key_types "D:/emhash/build_asan/Debug/test_special_key_types.exe")
  set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;173;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_special_key_types "D:/emhash/build_asan/Release/test_special_key_types.exe")
  set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;173;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_special_key_types "D:/emhash/build_asan/MinSizeRel/test_special_key_types.exe")
  set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;173;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_special_key_types "D:/emhash/build_asan/RelWithDebInfo/test_special_key_types.exe")
  set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;173;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_special_key_types NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_merge_correctness "D:/emhash/build_asan/Debug/test_merge_correctness.exe")
  set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;174;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_merge_correctness "D:/emhash/build_asan/Release/test_merge_correctness.exe")
  set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;174;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_merge_correctness "D:/emhash/build_asan/MinSizeRel/test_merge_correctness.exe")
  set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;174;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_merge_correctness "D:/emhash/build_asan/RelWithDebInfo/test_merge_correctness.exe")
  set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;174;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_merge_correctness NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(edge_test "D:/emhash/build_asan/Debug/edge_test.exe")
  set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;175;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(edge_test "D:/emhash/build_asan/Release/edge_test.exe")
  set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;175;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(edge_test "D:/emhash/build_asan/MinSizeRel/edge_test.exe")
  set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;175;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(edge_test "D:/emhash/build_asan/RelWithDebInfo/edge_test.exe")
  set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;175;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(edge_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_find_slot_bucket "D:/emhash/build_asan/Debug/test_find_slot_bucket.exe")
  set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;176;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_find_slot_bucket "D:/emhash/build_asan/Release/test_find_slot_bucket.exe")
  set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;176;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_find_slot_bucket "D:/emhash/build_asan/MinSizeRel/test_find_slot_bucket.exe")
  set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;176;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_find_slot_bucket "D:/emhash/build_asan/RelWithDebInfo/test_find_slot_bucket.exe")
  set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;176;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_find_slot_bucket NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_string_key_leak "D:/emhash/build_asan/Debug/test_string_key_leak.exe")
  set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;177;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_string_key_leak "D:/emhash/build_asan/Release/test_string_key_leak.exe")
  set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;177;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_string_key_leak "D:/emhash/build_asan/MinSizeRel/test_string_key_leak.exe")
  set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;177;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_string_key_leak "D:/emhash/build_asan/RelWithDebInfo/test_string_key_leak.exe")
  set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;177;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_string_key_leak NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_stress "D:/emhash/build_asan/Debug/test_stress.exe")
  set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;180;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_stress "D:/emhash/build_asan/Release/test_stress.exe")
  set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;180;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_stress "D:/emhash/build_asan/MinSizeRel/test_stress.exe")
  set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;180;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_stress "D:/emhash/build_asan/RelWithDebInfo/test_stress.exe")
  set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;180;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_stress NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_bad_hash_stress "D:/emhash/build_asan/Debug/test_bad_hash_stress.exe")
  set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;181;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_bad_hash_stress "D:/emhash/build_asan/Release/test_bad_hash_stress.exe")
  set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;181;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_bad_hash_stress "D:/emhash/build_asan/MinSizeRel/test_bad_hash_stress.exe")
  set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;181;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_bad_hash_stress "D:/emhash/build_asan/RelWithDebInfo/test_bad_hash_stress.exe")
  set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;181;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_bad_hash_stress NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stress_fix "D:/emhash/build_asan/Debug/stress_fix.exe")
  set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;182;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stress_fix "D:/emhash/build_asan/Release/stress_fix.exe")
  set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;182;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stress_fix "D:/emhash/build_asan/MinSizeRel/stress_fix.exe")
  set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;182;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stress_fix "D:/emhash/build_asan/RelWithDebInfo/stress_fix.exe")
  set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;182;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(stress_fix NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(highload_test "D:/emhash/build_asan/Debug/highload_test.exe")
  set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;183;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(highload_test "D:/emhash/build_asan/Release/highload_test.exe")
  set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;183;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(highload_test "D:/emhash/build_asan/MinSizeRel/highload_test.exe")
  set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;183;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(highload_test "D:/emhash/build_asan/RelWithDebInfo/highload_test.exe")
  set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;183;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(highload_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emhash5_stress "D:/emhash/build_asan/Debug/test_emhash5_stress.exe")
  set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;184;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emhash5_stress "D:/emhash/build_asan/Release/test_emhash5_stress.exe")
  set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;184;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emhash5_stress "D:/emhash/build_asan/MinSizeRel/test_emhash5_stress.exe")
  set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;184;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emhash5_stress "D:/emhash/build_asan/RelWithDebInfo/test_emhash5_stress.exe")
  set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;184;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emhash5_stress NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_emhash5_hifi "D:/emhash/build_asan/Debug/test_emhash5_hifi.exe")
  set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;185;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_emhash5_hifi "D:/emhash/build_asan/Release/test_emhash5_hifi.exe")
  set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;185;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_emhash5_hifi "D:/emhash/build_asan/MinSizeRel/test_emhash5_hifi.exe")
  set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;185;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_emhash5_hifi "D:/emhash/build_asan/RelWithDebInfo/test_emhash5_hifi.exe")
  set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;185;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_emhash5_hifi NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_attack "D:/emhash/build_asan/Debug/test_attack.exe")
  set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;188;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_attack "D:/emhash/build_asan/Release/test_attack.exe")
  set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;188;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_attack "D:/emhash/build_asan/MinSizeRel/test_attack.exe")
  set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;188;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_attack "D:/emhash/build_asan/RelWithDebInfo/test_attack.exe")
  set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;188;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_attack NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hash_attack5 "D:/emhash/build_asan/Debug/hash_attack5.exe")
  set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;189;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hash_attack5 "D:/emhash/build_asan/Release/hash_attack5.exe")
  set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;189;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hash_attack5 "D:/emhash/build_asan/MinSizeRel/hash_attack5.exe")
  set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;189;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hash_attack5 "D:/emhash/build_asan/RelWithDebInfo/hash_attack5.exe")
  set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;189;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(hash_attack5 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hash_attack7 "D:/emhash/build_asan/Debug/hash_attack7.exe")
  set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;190;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hash_attack7 "D:/emhash/build_asan/Release/hash_attack7.exe")
  set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;190;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hash_attack7 "D:/emhash/build_asan/MinSizeRel/hash_attack7.exe")
  set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;190;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hash_attack7 "D:/emhash/build_asan/RelWithDebInfo/hash_attack7.exe")
  set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;190;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(hash_attack7 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_debug "D:/emhash/build_asan/Debug/test_debug.exe")
  set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;193;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_debug "D:/emhash/build_asan/Release/test_debug.exe")
  set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;193;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_debug "D:/emhash/build_asan/MinSizeRel/test_debug.exe")
  set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;193;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_debug "D:/emhash/build_asan/RelWithDebInfo/test_debug.exe")
  set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "D:/emhash/tests/CMakeLists.txt;152;add_test;D:/emhash/tests/CMakeLists.txt;193;emhash_register_test;D:/emhash/tests/CMakeLists.txt;0;")
else()
  add_test(test_debug NOT_AVAILABLE)
endif()
