# CMake generated Testfile for 
# Source directory: /mnt/d/emhash/tests
# Build directory: /mnt/d/emhash/build_ci
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(reproduce_emhash8_bug "/mnt/d/emhash/build_ci/reproduce_emhash8_bug")
set_tests_properties(reproduce_emhash8_bug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;157;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_verify "/mnt/d/emhash/build_ci/test_verify")
set_tests_properties(test_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;160;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(quick_test8 "/mnt/d/emhash/build_ci/quick_test8")
set_tests_properties(quick_test8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;161;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash58 "/mnt/d/emhash/build_ci/test_emhash58")
set_tests_properties(test_emhash58 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;162;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_hidden_bugs8 "/mnt/d/emhash/build_ci/test_hidden_bugs8")
set_tests_properties(test_hidden_bugs8 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;163;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_extreme "/mnt/d/emhash/build_ci/test_extreme")
set_tests_properties(test_extreme PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;164;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_interface_combo "/mnt/d/emhash/build_ci/test_interface_combo")
set_tests_properties(test_interface_combo PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;165;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_verify "/mnt/d/emhash/build_ci/test_emhash5_verify")
set_tests_properties(test_emhash5_verify PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;166;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash_allocator "/mnt/d/emhash/build_ci/test_emhash_allocator")
set_tests_properties(test_emhash_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;167;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_functional_edge "/mnt/d/emhash/build_ci/test_functional_edge")
set_tests_properties(test_functional_edge PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;168;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashset_allocator "/mnt/d/emhash/build_ci/test_hashset_allocator")
set_tests_properties(test_hashset_allocator PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;169;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emilib_comprehensive "/mnt/d/emhash/build_ci/test_emilib_comprehensive")
set_tests_properties(test_emilib_comprehensive PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;170;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_size_sweep "/mnt/d/emhash/build_ci/test_size_sweep")
set_tests_properties(test_size_sweep PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;171;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashmap_full_api "/mnt/d/emhash/build_ci/test_hashmap_full_api")
set_tests_properties(test_hashmap_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;172;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_hashset_full_api "/mnt/d/emhash/build_ci/test_hashset_full_api")
set_tests_properties(test_hashset_full_api PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;173;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_special_key_types "/mnt/d/emhash/build_ci/test_special_key_types")
set_tests_properties(test_special_key_types PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;174;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_merge_correctness "/mnt/d/emhash/build_ci/test_merge_correctness")
set_tests_properties(test_merge_correctness PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;175;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(edge_test "/mnt/d/emhash/build_ci/edge_test")
set_tests_properties(edge_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;176;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_find_slot_bucket "/mnt/d/emhash/build_ci/test_find_slot_bucket")
set_tests_properties(test_find_slot_bucket PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;177;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_string_key_leak "/mnt/d/emhash/build_ci/test_string_key_leak")
set_tests_properties(test_string_key_leak PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;178;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_stress "/mnt/d/emhash/build_ci/test_stress")
set_tests_properties(test_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;181;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_bad_hash_stress "/mnt/d/emhash/build_ci/test_bad_hash_stress")
set_tests_properties(test_bad_hash_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;182;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(stress_fix "/mnt/d/emhash/build_ci/stress_fix")
set_tests_properties(stress_fix PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;183;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(highload_test "/mnt/d/emhash/build_ci/highload_test")
set_tests_properties(highload_test PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;184;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_stress "/mnt/d/emhash/build_ci/test_emhash5_stress")
set_tests_properties(test_emhash5_stress PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;185;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_emhash5_hifi "/mnt/d/emhash/build_ci/test_emhash5_hifi")
set_tests_properties(test_emhash5_hifi PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;186;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_attack "/mnt/d/emhash/build_ci/test_attack")
set_tests_properties(test_attack PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;189;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(hash_attack5 "/mnt/d/emhash/build_ci/hash_attack5")
set_tests_properties(hash_attack5 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;190;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(hash_attack7 "/mnt/d/emhash/build_ci/hash_attack7")
set_tests_properties(hash_attack7 PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;191;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
add_test(test_debug "/mnt/d/emhash/build_ci/test_debug")
set_tests_properties(test_debug PROPERTIES  LABELS "emhash" _BACKTRACE_TRIPLES "/mnt/d/emhash/tests/CMakeLists.txt;153;add_test;/mnt/d/emhash/tests/CMakeLists.txt;194;emhash_register_test;/mnt/d/emhash/tests/CMakeLists.txt;0;")
