#!/usr/bin/env bash
# Amalgamate emhash headers into single-header distributions
# Usage: ./scripts/amalgamate.sh [version]
# Output: dist/emhash7_single.hpp, dist/emhash8_single.hpp, etc.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION="${1:-$(cat "$ROOT_DIR/VERSION" 2>/dev/null || echo "dev")}"
DIST_DIR="$ROOT_DIR/dist"

mkdir -p "$DIST_DIR"

amalgamate() {
    local src="$1"
    local base="$(basename "$src" .hpp)"
    local output="$DIST_DIR/${base}_single.hpp"
    local guard="$(echo "$base" | tr '[:lower:]' '[:upper:]')_SINGLE_HPP"

    echo "// emhash ${base} single-header distribution" > "$output"
    echo "// Version: ${VERSION}" >> "$output"
    echo "// Generated by scripts/amalgamate.sh - DO NOT EDIT" >> "$output"
    echo "// Original source: https://github.com/ktprime/emhash" >> "$output"
    echo "" >> "$output"
    echo "#ifndef ${guard}" >> "$output"
    echo "#define ${guard}" >> "$output"
    echo "" >> "$output"

    # Process includes: inline local headers, skip system headers
    while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*#\ *include\ \"([^\"]+)\" ]]; then
            local inc="${BASH_REMATCH[1]}"
            local inc_path="$ROOT_DIR/$inc"
            if [[ -f "$inc_path" ]]; then
                # Inline local header (skip its own include guard and pragma once)
                echo "// --- begin included: $inc ---" >> "$output"
                sed '/^#pragma once$/d; /^#ifndef.*_HPP/,/^#define.*_HPP$/d' "$inc_path" | \
                    sed '/^#endif.*\/\/.*_HPP/d' >> "$output"
                echo "// --- end included: $inc ---" >> "$output"
                echo "" >> "$output"
            else
                echo "$line" >> "$output"
            fi
        elif [[ "$line" =~ ^[[:space:]]*#\ *include\ \< ]]; then
            echo "$line" >> "$output"
        elif [[ "$line" =~ ^[[:space:]]*#\ *pragma\ once ]]; then
            : # skip, we have our own guard
        else
            echo "$line" >> "$output"
        fi
    done < "$src"

    echo "" >> "$output"
    echo "#endif // ${guard}" >> "$output"

    local lines=$(wc -l < "$output")
    echo "Created $output ($lines lines)"
}

# Generate single-header for each main implementation
for hpp in hash_table5 hash_table6 hash_table7 hash_table8; do
    if [[ -f "$ROOT_DIR/${hpp}.hpp" ]]; then
        amalgamate "$ROOT_DIR/${hpp}.hpp"
    fi
done

echo ""
echo "Done. Single-header files are in $DIST_DIR/"
echo "Users can copy one file into their project and #include it."
