#!/usr/bin/env bash
# Generate amalgamated single-header distribution for emhash
# Usage: ./scripts/amalgamate.sh [version]
# Output: dist/emhash.hpp

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INCLUDE_DIR="$ROOT_DIR/include"

VERSION="${1:-dev}"
OUTPUT_DIR="$ROOT_DIR/dist"
OUTPUT="$OUTPUT_DIR/emhash.hpp"

mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT" <<EOF
// emhash $VERSION - Amalgamated single-header distribution
// https://github.com/ktprime/emhash
//
// Generated by scripts/amalgamate.sh - DO NOT EDIT
// This file combines all emhash and emilib headers into a single include.
// License: MIT
//
// Usage:
//   #define EMHASH_AMALGAMATED
//   #include "emhash.hpp"

#ifndef EMHASH_AMALGAMATED_H
#define EMHASH_AMALGAMATED_H

EOF

# Collect all headers in dependency order
HEADERS=(
    "emhash/config.hpp"
    "emhash/hash_table5.hpp"
    "emhash/hash_table6.hpp"
    "emhash/hash_table7.hpp"
    "emhash/hash_table8.hpp"
    "emhash/hash_set2.hpp"
    "emhash/hash_set3.hpp"
    "emhash/hash_set4.hpp"
    "emhash/hash_set8.hpp"
    "emhash/lru_size.hpp"
    "emhash/lru_time.hpp"
    "emilib/emihmap1.hpp"
    "emilib/emihmap2.hpp"
    "emilib/emihmap3.hpp"
    "emilib/emihset2.hpp"
    "emilib/emihset3.hpp"
)

for header in "${HEADERS[@]}"; do
    if [ -f "$INCLUDE_DIR/$header" ]; then
        echo "// ========================================================================" >> "$OUTPUT"
        echo "// $header" >> "$OUTPUT"
        echo "// ========================================================================" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        # Strip #pragma once, internal config include, and leading comments, keep the rest
        sed -e '/^#pragma once$/d' -e '/^#include "emhash\/config\.hpp"$/d' "$INCLUDE_DIR/$header" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    else
        echo "WARNING: $header not found, skipping" >&2
    fi
done

echo "#endif // EMHASH_AMALGAMATED_H" >> "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT") lines)"
